"""Add number_of_minutes column to activity_tracker

Revision ID: 85f874983c70
Revises: f220b073b53d
Create Date: 2025-07-04 09:47:06.596849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f874983c70'
down_revision: Union[str, None] = 'f220b073b53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'activity_tracker',
        sa.Column('number_of_minutes', sa.Integer(), nullable=False, server_default="0")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_tracker', 'number_of_minutes')
    # ### end Alembic commands ###
