"""blocked_user_ids list a mutable

Revision ID: bdf9f59ddc36
Revises: f1597b4baefd
Create Date: 2025-06-13 23:09:13.305220

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bdf9f59ddc36"
down_revision: Union[str, None] = "f1597b4baefd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
