"""added hate_count and is_suspended

Revision ID: 04bca1b0c544
Revises: 4f9696cc82c1
Create Date: 2025-06-23 00:51:50.481427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bca1b0c544'
down_revision: Union[str, None] = '4f9696cc82c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('hate_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_data', sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'is_suspended')
    op.drop_column('user_data', 'hate_count')
    # ### end Alembic commands ###
