"""fixed is_active to false by default

Revision ID: 0656d8310095
Revises: 14d50734a3c3
Create Date: 2025-06-11 13:49:08.353715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0656d8310095"
down_revision: Union[str, None] = "14d50734a3c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "status")
    # ### end Alembic commands ###
