"""added created_at to Friendship  table

Revision ID: 389cabc131d1
Revises: d30445c16e8e
Create Date: 2025-06-09 20:40:39.248798

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "389cabc131d1"
down_revision: Union[str, None] = "d30445c16e8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("friendship", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("friendship", "created_at")
    # ### end Alembic commands ###
