"""added failed_attempts filed to UserData

Revision ID: 4d2861e1153a
Revises: d3512f88bdd5
Create Date: 2025-06-11 22:41:46.100060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d2861e1153a"
down_revision: Union[str, None] = "d3512f88bdd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_data", sa.Column("failed_attempts", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_data", "failed_attempts")
    # ### end Alembic commands ###
