"""change interests column to list[str]

Revision ID: 4f9696cc82c1
Revises: bdf9f59ddc36
Create Date: 2025-06-21 03:09:33.593564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f9696cc82c1'
down_revision: Union[str, None] = 'bdf9f59ddc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('matchmaking', 'interests',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=sa.ARRAY(sa.String()),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matchmaking', 'interests',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
