"""add profile_pic to user_data

Revision ID: c002c83037a9
Revises: 1f3e700925fd
Create Date: 2025-06-13 18:07:35.207799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c002c83037a9"
down_revision: Union[str, None] = "1f3e700925fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_data", sa.Column("profile_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_data", "profile_image")
    # ### end Alembic commands ###
