"""added sent_at to FriendRequest table

Revision ID: d30445c16e8e
Revises: 9b1bba4bcbbd
Create Date: 2025-06-09 19:38:11.543139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d30445c16e8e"
down_revision: Union[str, None] = "9b1bba4bcbbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("friend_requests", sa.Column("sent_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("friend_requests", "sent_at")
    # ### end Alembic commands ###
