"""added is_locked for login rate limiting and locking the user after 3 attempts/min

Revision ID: d3512f88bdd5
Revises: 0656d8310095
Create Date: 2025-06-11 22:20:17.608294

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3512f88bdd5"
down_revision: Union[str, None] = "0656d8310095"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chat_messages SET status = 'sent' WHERE status IS NULL")

    op.alter_column(
        "chat_messages",
        "status",
        existing_type=sa.String(),
        nullable=False,
        server_default="sent",
    )

    op.add_column("user_data", sa.Column("is_locked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_data", "is_locked")
    op.alter_column(
        "chat_messages", "status", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
