"""ddd blocked_user_ids to UserData

Revision ID: f1597b4baefd
Revises: f21364bf9d16
Create Date: 2025-06-13 22:48:27.783302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1597b4baefd"
down_revision: Union[str, None] = "f21364bf9d16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_data",
        sa.Column(
            "blocked_user_ids",
            sa.ARRAY(sa.Integer()),
            nullable=False,
            server_default="{}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_data", "blocked_user_ids")
    # ### end Alembic commands ###
