"""add last_practiced_date to activity_tracker

Revision ID: f220b073b53d
Revises: 57d8ebfcba20
Create Date: 2025-06-30 19:45:26.954435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f220b073b53d'
down_revision: Union[str, None] = '57d8ebfcba20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_tracker', sa.Column('last_practiced_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_tracker', 'last_practiced_date')
    # ### end Alembic commands ###
