name: Fluently CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      BASE_URL: http://localhost:8000
      SECRET_KEY: testing-secret
      JWT_ISSUER: test-issuer
      JWT_AUDIENCE: test-audience

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      # ---------- lint ----------
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=88

      # ---------- type checking ----------
      - name: Type check with mypy
        run: |
          pip install mypy
          mypy app

      # ---------- format check ----------
      - name: Check code formatting with black
        run: |
          pip install black
          black --check app tests

      # ---------- Security scan ----------
      - name: Security audit with pip-audit
        run: |
          pip install pip-audit
          pip-audit

      # ---------- Test section ----------
      # - name: Run tests with pytest
      #   run: |
      #     pip install pytest pytest-cov
      #     pytest --cov=app tests/